
version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    user: 1000:1000
    restart: always
    depends_on:
      - "dind"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_VERIFY=1
    ports:
      - "2376:2376"
      - "3000:3000"
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins
  dind:
    image: docker:dind
    restart: always
    networks: jenkins
    privileged: true
    command: --storage-driver=overlay2

volumes:
  jenkins-docker-certs: {}

networks:
  jenkins:

