pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'pwd'
		        sh 'cd webapp'
                sh 'pwd'
                sh 'npm install --save-dev cross-env'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing..."'
		        sh 'cd webapp'
                sh 'npm test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Delivering..."'
                
                script {
                    def myEnv = docker.build('myWebApp:snapshot')
                    myEnv.inside {
			            sh 'cd webapp'
                        sh 'npm run build'
                    }
                }
            }
        }
    }
}
