def PIDBUILDAPP

pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Installing Dependencies..."'
                dir('webapp') {
                    sh 'npm install --save-dev cross-env'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing..."'
                dir ('webapp') {
                    sh 'npm test'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Delivering..."'
                dir ('webapp') {
                    // script {
                    //     def myEnv = docker.build('myWebApp:snapshot')
                    //     myEnv.inside {
                    //         sh 'npm run-script build'
                    //     }
                    // }
                    sh 'npm run build'
                    script {
                        PIDBUILDAPP = sh (
                            script: "npm start & echo \$!",
                            returnStdout: true
                        ).trim()
                    }
                    echo PIDBUILDAPP
                    sh 'sleep 1'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    echo PIDBUILDAPP
                    // sh 'echo "Killing PID: $PIDBUILDAPP"'
                    // sh 'kill $PIDBUILDAPP'
                }
            }
        }
    }
}
